blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/thedaviddias/links-base/discussions
    about: Use GitHub Discussions for questions and discussions
