name: Release Please

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Create release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}

    steps:
      - uses: googleapis/release-please-action@v4
        name: Create release with release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json

  publish-dry-run:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    name: Dry run - show what would be published
    steps:
      - uses: actions/checkout@v4

      - name: Setup project dependencies
        uses: ./.github/workflows/setup-node
        id: setup-node

      - name: Build packages
        run: pnpm build:cli

      - name: Show release info
        run: |
          echo "🎉 New release(s) created!"
          echo "Released paths: ${{ needs.release-please.outputs.paths_released }}"

      - name: Dry Run - Package Analysis
        run: |
          echo "📦 Analyzing package that would be published..."
          cd packages/create-links-base

          echo "📋 Package.json contents:"
          cat package.json | jq .

          echo "\n📦 Files that would be published:"
          npm pack --dry-run

          echo "\n🔍 Version details:"
          echo "Version: $(node -p "require('./package.json').version")"
          echo "Name: $(node -p "require('./package.json').name")"

          echo "\n📁 Dist folder contents:"
          ls -la dist/

          echo "\n✨ Ready for production release!"
          echo "To enable actual publishing, uncomment the publish job in the workflow"

  # Uncomment this job when ready for production releases
  # publish:
  #   needs: [release-please, publish-dry-run]
  #   if: ${{ needs.release-please.outputs.releases_created }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Setup project dependencies
  #       uses: ./.github/workflows/setup-node
  #       id: setup-node
  #
  #     - name: Build packages
  #       run: pnpm build:cli
  #
  #     - name: Publish to NPM
  #       run: pnpm publish:cli
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
