name: Codecov test

on: [push, pull_request]

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup project dependencies
        uses: ./.github/workflows/setup-node

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: links-base-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: thedaviddias/links-base
          directory: ./apps/app/coverage
          files: ./apps/app/coverage/lcov.info
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
