name: Release Please

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Create release

    steps:
      - uses: googleapis/release-please-action@v4
        name: Create release with release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
